apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx  # Added a space after the colon for correct YAML syntax.
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:  # This line was correctly indented; it aligns with 'selector' and 'replicas' under 'spec'.
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.image }}"  # Ensure there are spaces inside the curly braces for readability.
        ports:
        - containerPort: 80
        env:
        - name: DATE
          value: {{ .Values.env }}  # Ensure there are spaces inside the curly braces for readability.
